{% set name = "veracitools" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c86d36a8567b3da1b0ac296b4668cb9a9ea8e18f3c8c18eb88373aca8312a37

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pytest

test:
  imports:
    - veracitools

about:
  home: https://github.com/pepkit/veracitools/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Testing utilities

extra:
  recipe-maintainers:
    - michalstolarczyk
